export enum ApplicationStatus {
  SUBMITTED = 'SUBMITTED',
  IN_PROGRESS = 'IN_PROGRESS',
  OFFER = 'OFFER',
  REJECTED = 'REJECTED',
  OA_RECEIVED = 'OA_RECEIVED',
  WITHDRAWN = 'WITHDRAWN',
}

export enum InterviewType {
  CRITICAL_THINKING = 'CRITICAL_THINKING',
  CODE_REVIEW = 'CODE_REVIEW',
  BEHAVIORIAL = 'BEHAVIORIAL',
  TECHNICAL = 'TECHNICAL',
  RECRUITER_SCREEN = 'RECRUITER_SCREEN',
  DEBUG = 'DEBUG',
  SYSTEM_DESIGN = 'SYSTEM_DESIGN',
  TRIVIA = 'TRIVIA',
  PROJECT_WALKTHROUGH = 'PROJECT_WALKTHROUGH',
  PRACTICAL = 'PRACTICAL',
  HIRING_MANAGER = 'HIRING_MANAGER',
}

export enum InterviewStatus {
  PASSED = 'PASSED',
  FAILED = 'FAILED',
  WITHDRAWN = 'WITHDRAWN',
  UPCOMING = 'UPCOMING',
  PENDING = 'PENDING',
}

export enum InvitationStatus {
  ACCEPTED = 'ACCEPTED',
  EXPIRED = 'EXPIRED',
  PENDING = 'PENDING',
  REVOKED = 'REVOKED',
}

export enum Location {
  US = 'US',
  CANADA = 'CANADA',
}

export enum LinkStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum Role {
  ADMIN = 'ADMIN',
  MODERATOR = 'MODERATOR',
  USER = 'USER',
}

export enum Permission {
  GET_ALL_PENDING_JOB_LINKS = 'GET_ALL_PENDING_JOB_LINKS',
  APPROVE_JOB_LINK = 'APPROVE_JOB_LINK ',
  REJECT_JOB_LINK = 'REJECT_JOB_LINK',
  UPDATE_JOB_POSTING = 'UPDATE_JOB_POSTING',
  DELETE_JOB_POSTING = 'DELETE_JOB_POSTING',
  GET_ALL_INVITATIONS = 'GET_ALL_INVITATIONS',
  CREATE_INVITATION = 'CREATE_INVITATION',
  REVOKE_INVITATION = 'REVOKE_INVITATION',
}
