export enum ApplicationStatus {
  SUBMITTED = 'SUBMITTED',
  IN_PROGRESS = 'IN_PROGRESS',
  OFFER = 'OFFER',
  REJECTED = 'REJECTED',
  OA_RECEIVED = 'OA_RECEIVED',
  WITHDRAWN = 'WITHDRAWN',
}

export enum InterviewType {
  CRITICAL_THINKING = 'CRITICAL_THINKING',
  CODE_REVIEW = 'CODE_REVIEW',
  BEHAVIORIAL = 'BEHAVIORIAL',
  TECHNICAL = 'TECHNICAL',
  RECRUITER_SCREEN = 'RECRUITER_SCREEN',
  DEBUG = 'DEBUG',
  SYSTEM_DESIGN = 'SYSTEM_DESIGN',
  TRIVIA = 'TRIVIA',
  PROJECT_WALKTHROUGH = 'PROJECT_WALKTHROUGH',
  PRACTICAL = 'PRACTICAL',
  HIRING_MANAGER = 'HIRING_MANAGER',
}

export enum InterviewStatus {
  PASSED = 'PASSED',
  FAILED = 'FAILED',
  WITHDRAWN = 'WITHDRAWN',
  UPCOMING = 'UPCOMING',
  PENDING = 'PENDING',
}

export enum InvitationStatus {
  ACCEPTED = 'ACCEPTED',
  EXPIRED = 'EXPIRED',
  PENDING = 'PENDING',
  REVOKED = 'REVOKED',
}

export enum JobPostingLocation {
  US = 'US',
  CANADA = 'CANADA',
}

export enum LinkStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum UserRole {
  ADMIN = 'ADMIN',
  MODERATOR = 'MODERATOR',
  USER = 'USER',
}

export enum ProgramRole {
  PROGRAM_MANAGER = 'PROGRAM_MANAGER',
  PROGRAM_FOUNDER = 'PROGRAM_FOUNDER',
  PROGRAM_ADVISOR = 'PROGRAM_ADVISOR',
  SWE_PROGRAM_LEAD = 'SWE_PROGRAM_LEAD',
  SWE_RISING_LEAD = 'SWE_RISING_LEAD',
  SWE_LEAD = 'SWE_LEAD',
  SWE_INACTIVE_LEAD = 'SWE_INACTIVE_LEAD',
  SWE_MENTOR = 'SWE_MENTOR',
  SWE_EXMENTEE_INACTIVE_MENTOR = 'SWE_EXMENTEE_INACTIVE_MENTOR',
  SWE_EXMENTEE_MENTOR = 'SWE_EXMENTEE_MENTOR',
  SWE_EXMENTEE_LOGISTICS_SUPPORT = 'SWE_EXMENTEE_LOGISTICS_SUPPORT',
  SWE_MENTEE = 'SWE_MENTEE',
  PD_MENTOR = 'PD_MENTOR',
  PD_MENTEE = 'PD_MENTEE',
}

export enum Permission {
  VIEW_JOB_LINK = 'VIEW_JOB_LINK',
  CREATE_JOB_LINK = 'CREATE_JOB_LINK',
  MANAGE_JOB_LINK = 'MANAGE_JOB_LINK',

  VIEW_JOB_POSTING = 'VIEW_JOB_POSTING',
  MANAGE_JOB_POSTING = 'MANAGE_JOB_POSTING',

  VIEW_INVITATION = 'VIEW_INVITATION',
  MANAGE_INVITATION = 'MANAGE_INVITATION',

  VIEW_APPLICATION = 'VIEW_APPLICATION',
  MANAGE_APPLICATION = 'MANAGE_APPLICATION',
}

export enum InterestLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
}

export enum Department {
  SWE = 'SWE',
  PD = 'PD',
}
