export enum LinkValidationErrorType {
  SITE_REPORTED_MALICIOUS = 'SITE_REPORTED_MALICIOUS',
  SAFETY_API_FAILED = 'SAFETY_API_FAILED',
  NETWORK_ERROR = 'NETWORK_ERROR',
  SITE_UNREACHABLE = 'SITE_UNREACHABLE',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}
export enum MaliciousLinkErrorType {
  SITE_REPORTED_MALICIOUS = 'SITE_REPORTED_MALICIOUS',
  SAFETY_API_FAILED = 'SAFETY_API_FAILED',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}
