// This file is auto-generated by scripts/generate-metadata.ts
// Do not edit this file directly.

import mdImport_2023_04_30_developer_productivity from '#vtmp/web-client/blogs/content/vtmp-2023/2023-04-30-developer-productivity.md';
import mdImport_2023_04_30_tools_for_team from '#vtmp/web-client/blogs/content/vtmp-2023/2023-04-30-tools-for-team.md';
import mdImport_2023_04_30_using_git from '#vtmp/web-client/blogs/content/vtmp-2023/2023-04-30-using-git.md';
import mdImport_2023_07_30_mentorship_half_way_reflection from '#vtmp/web-client/blogs/content/vtmp-2023/2023-07-30-mentorship-half-way-reflection.md';
import mdImport_2023_08_15_team1_2023 from '#vtmp/web-client/blogs/content/vtmp-2023/2023-08-15-team1-2023.md';
import mdImport_2023_08_15_team2_2023 from '#vtmp/web-client/blogs/content/vtmp-2023/2023-08-15-team2-2023.md';
import mdImport_2023_08_15_team3_2023 from '#vtmp/web-client/blogs/content/vtmp-2023/2023-08-15-team3-2023.md';
import mdImport_2023_12_15_summary_2023 from '#vtmp/web-client/blogs/content/vtmp-2023/2023-12-15-summary-2023.md';
import mdImport_2024_03_22_technical_workshops_2024 from '#vtmp/web-client/blogs/content/vtmp-2024/2024-03-22-technical-workshops-2024.md';
import mdImport_2024_04_05_hunt_for_job from '#vtmp/web-client/blogs/content/vtmp-2024/2024-04-05-hunt-for-job.md';
import mdImport_2024_11_08_conference_tips from '#vtmp/web-client/blogs/content/vtmp-2024/2024-11-08-conference-tips.md';
import mdImport_2024_11_21_advanced_group_project from '#vtmp/web-client/blogs/content/vtmp-2024/2024-11-21-advanced-group-project.md';
import mdImport_2024_11_23_review_vtmp_experience from '#vtmp/web-client/blogs/content/vtmp-2024/2024-11-23-review-vtmp-experience.md';
import mdImport_2024_12_02_i_wish_i_knew from '#vtmp/web-client/blogs/content/vtmp-2024/2024-12-02-i-wish-i-knew.md';
import mdImport_2024_12_07_summary_2024 from '#vtmp/web-client/blogs/content/vtmp-2024/2024-12-07-summary-2024.md';
import mdImport_2025_03_02_env_setup_mac from '#vtmp/web-client/blogs/content/vtmp-2025/2025-03-02-env-setup-mac.md';
import mdImport_2025_03_02_env_setup_windows from '#vtmp/web-client/blogs/content/vtmp-2025/2025-03-02-env-setup-windows.md';
import { BlogMetadata } from '#vtmp/web-client/types';

export const allBlogsMetadata: BlogMetadata[] = [
  {
    title: 'Environment Setup for Windows',
    authors: ['Phuc Khang'],
    contributors: ['Hoang Nguyen'],
    description:
      'Guide to setup environment that is ready for group project for Windows (Git, Github, VSCode, Node.js, React.js, MongoDB).',
    date: '2025-03-02T00:00:00.000Z',
    tags: ['setup', 'tools'],
    banner:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Unofficial_Windows_logo_variant_-_2002%E2%80%932012_%28Multicolored%29.svg/170px-Unofficial_Windows_logo_variant_-_2002%E2%80%932012_%28Multicolored%29.svg.png',
    name: '2025-03-02-env-setup-windows',
    filepath: mdImport_2025_03_02_env_setup_windows,
  },
  {
    title: 'Environment Setup for MacOS',
    authors: ['Hoang Nguyen'],
    contributors: ['Phuc Khang'],
    description:
      'Guide to setup environment that is ready for group project for MacOS (Git, Github, VSCode, Node.js, React.js, MongoDB).',
    date: '2025-03-02T00:00:00.000Z',
    tags: ['setup', 'tools'],
    banner:
      'https://d1csarkz8obe9u.cloudfront.net/posterpreviews/mac-logo-design-template-8fe7b3dedb88be5575e790e208c17b25_screen.jpg?ts=1662442689',
    name: '2025-03-02-env-setup-mac',
    filepath: mdImport_2025_03_02_env_setup_mac,
  },
  {
    title: 'Viet Tech 2024 summary',
    authors: ['Khoa Le'],
    description:
      'Looking back at the second year running Viet Tech Mentorship Program',
    date: '2024-12-07T00:00:00.000Z',
    tags: ['reflection', 'announcement'],
    banner:
      'https://res.cloudinary.com/khoa165/image/upload/v1740989282/viettech/offers2024.png',
    name: '2024-12-07-summary-2024',
    contributors: [],
    filepath: mdImport_2024_12_07_summary_2024,
  },
  {
    title: 'Mấy điều nhỏ nhặt em ước mình biết sớm hơn khi apply internship',
    authors: ['Trang Do', 'Ngoc Anh'],
    description:
      'Thời điểm này cũng đã cuối năm nên em muốn post một bài nho nhỏ share về những gì em học được qua cả mùa lầy lội apply internship năm nay. Bài post này em viết cùng với Ngọc Anh, cũng là mentee trong VTMP. Một số điều tụi em sắp chia sẻ dưới đây có thể hơi personal và là đúc kết của riêng tụi em, nhưng hy vọng cho mọi người một insight mới và phần nào động viên những bạn chưa gặp may mắn trong thời gian vừa rồi tiếp tục cố gắng.',
    date: '2024-12-02T00:00:00.000Z',
    tags: ['reflection', 'advice'],
    banner:
      'https://res.cloudinary.com/khoa165/image/upload/v1718192551/viettech/VTMP_logo.png',
    name: '2024-12-02-i-wish-i-knew',
    contributors: [],
    filepath: mdImport_2024_12_02_i_wish_i_knew,
  },
  {
    title: 'Trải Nghiệm Tham Gia Viet Tech Mentorship Program',
    authors: ['Van Nguyen'],
    description:
      'Mình là Thanh Vân, mentee của Viet Tech Mentorship Program (VTMP) mùa hai. Mình viết bài này để chia sẻ trải nghiệm tham gia mentorship trong gần một năm vừa qua, hy vọng sẽ mang đến cho các bạn cái nhìn chân thật, đặc biệt là những ai đang muốn nộp đơn vào VTMP mùa ba!',
    date: '2024-11-23T00:00:00.000Z',
    tags: ['reflection'],
    banner:
      'https://res.cloudinary.com/khoa165/image/upload/v1718192551/viettech/VTMP_logo.png',
    name: '2024-11-23-review-vtmp-experience',
    contributors: [],
    filepath: mdImport_2024_11_23_review_vtmp_experience,
  },
  {
    title: 'How did we go beyond CRUD in a personal project?',
    authors: ['Hoang Nguyen'],
    contributors: ['Ha Linh', 'Khanh Linh', 'Huu Khang'],
    description:
      'Hello everyone, I’m Hoang, a mentee of the Viet Tech Mentorship Program (cohort 2024). This past summer, my team worked on a project called Cupid. Initially, we struggled to figure out how to make Cupid more than just a basic web app. Thanks to the dedicated guidance from our project advisors — Khoa Le and Nick Doan — we were able to elevate Cupid to the next level.',
    date: '2024-11-21T00:00:00.000Z',
    tags: ['reflection', 'technical'],
    banner:
      'https://res.cloudinary.com/khoa165/image/upload/v1740992775/viettech/cupid.jpg',
    name: '2024-11-21-advanced-group-project',
    filepath: mdImport_2024_11_21_advanced_group_project,
  },
  {
    title: 'Kinh nghiệm để có 3 interviews tại GHC',
    authors: ['Quynh Tran'],
    description:
      'Em là Như Quỳnh, mentee của Viet Tech Mentorship Program năm nay. Trước khi đi GHC, em đã đọc nhiều bài chia sẻ kinh nghiệm từ các anh chị trong group nhờ vậy mà trải nghiệm GHC của em khá tốt. Em đã may mắn có được 3 onsite interviews và muốn chia sẻ lại kinh nghiệm của mình cho những bạn sắp đi conference nói chung và GHC nói riêng ạ.',
    date: '2024-11-08T00:00:00.000Z',
    tags: ['reflection', 'advice'],
    banner:
      'https://res.cloudinary.com/khoa165/image/upload/v1718192551/viettech/VTMP_logo.png',
    name: '2024-11-08-conference-tips',
    contributors: [],
    filepath: mdImport_2024_11_08_conference_tips,
  },
  {
    title: "How to hunt for job - A beginner's view",
    authors: ['Quan Le'],
    description:
      'Mình rất may mắn khi tìm được internship tại Meta và mình viết bài này để chia sẻ về interview process from a beginner perspective, và những bài học mình học được từ Viet Tech Mentorship Program (VTMP). Mình mong là có thể giúp mấy bạn có background như mình và mong là mình có thể đóng góp 1 phần nhỏ trong hành trình này của bạn.',
    date: '2024-04-05T00:00:00.000Z',
    tags: ['reflection', 'advice'],
    banner:
      'https://res.cloudinary.com/khoa165/image/upload/v1718192551/viettech/VTMP_logo.png',
    name: '2024-04-05-hunt-for-job',
    contributors: [],
    filepath: mdImport_2024_04_05_hunt_for_job,
  },
  {
    title: 'Technical workshops 2024',
    authors: ['Khoa Le'],
    description:
      'Recordings from 2024 workshops - Git, HTML/CSS, Productivity, MERN',
    date: '2024-03-22T00:00:00.000Z',
    tags: ['resources'],
    name: '2024-03-22-technical-workshops-2024',
    contributors: [],
    filepath: mdImport_2024_03_22_technical_workshops_2024,
  },
  {
    title: 'Viet Tech 2023 summary',
    authors: ['Khoa Le'],
    description: 'How we did the first year of VT mentorship program',
    date: '2023-12-15T00:00:00.000Z',
    tags: ['reflection', 'announcement'],
    banner:
      'https://res.cloudinary.com/khoa165/image/upload/v1711094075/viettech/offers2023.png',
    name: '2023-12-15-summary-2023',
    contributors: [],
    filepath: mdImport_2023_12_15_summary_2023,
  },
  {
    title: 'Team 3 project - 2023',
    authors: ['Robin Hoang'],
    contributors: ['Jenny Quach', 'Dang Pham', 'Phuoc Ong'],
    description: 'Sharing our learnings from working on the group project',
    date: '2023-08-15T00:00:00.000Z',
    tags: ['project'],
    banner:
      'https://res.cloudinary.com/khoa165/image/upload/v1703826455/portfolio/Team3-2023.jpg',
    name: '2023-08-15-team3-2023',
    filepath: mdImport_2023_08_15_team3_2023,
  },
  {
    title: 'Team 2 project - 2023',
    authors: ['Khue Tang'],
    contributors: ['Phuong Cao', 'Ngoc Doan', 'Cuong Nguyen'],
    description: 'Sharing our learnings from working on the group project',
    date: '2023-08-15T00:00:00.000Z',
    tags: ['project'],
    banner:
      'https://res.cloudinary.com/khoa165/image/upload/v1711093793/portfolio/Team2-2023.jpg',
    name: '2023-08-15-team2-2023',
    filepath: mdImport_2023_08_15_team2_2023,
  },
  {
    title: 'Team 1 project - 2023',
    authors: ['Hieu Vuong'],
    contributors: ['Quan Le', 'Trang Vu', 'Thanh Nguyen'],
    description: 'Sharing our learnings from working on the group project',
    date: '2023-08-15T00:00:00.000Z',
    tags: ['project'],
    banner:
      'https://res.cloudinary.com/khoa165/image/upload/v1703824525/portfolio/Team1-2023.png',
    name: '2023-08-15-team1-2023',
    filepath: mdImport_2023_08_15_team1_2023,
  },
  {
    title: 'Mentorship half-way look back',
    authors: ['Khoa Le'],
    description:
      'Reflection on the past 4-5 months running this mentorship program',
    date: '2023-07-30T00:00:00.000Z',
    tags: ['reflection'],
    banner:
      'https://res.cloudinary.com/khoa165/image/upload/v1691083734/portfolio/VietTechBanner.png',
    name: '2023-07-30-mentorship-half-way-reflection',
    contributors: [],
    filepath: mdImport_2023_07_30_mentorship_half_way_reflection,
  },
  {
    title: 'Using Git for collaboration',
    authors: ['Khoa Le'],
    description:
      'Learn basic Git commands to help you collaborate with your group more effectively in the remote settings',
    date: '2023-04-30T00:00:00.000Z',
    tags: ['technical'],
    banner:
      'https://media.geeksforgeeks.org/wp-content/uploads/20190624140226/distvcs.png',
    name: '2023-04-30-using-git',
    contributors: [],
    filepath: mdImport_2023_04_30_using_git,
  },
  {
    title: 'Tools for team',
    authors: ['Khoa Le'],
    description: 'Basic tools and tips for collaboration with your team',
    date: '2023-04-30T00:00:00.000Z',
    tags: ['tools'],
    banner:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRP6f1aZz5SvNRRPfLMN9bspCSsHUlDtLUDSQ&usqp=CAU',
    name: '2023-04-30-tools-for-team',
    contributors: [],
    filepath: mdImport_2023_04_30_tools_for_team,
  },
  {
    title: 'Developer productivity hacks',
    authors: ['Khoa Le'],
    description:
      'Bootstrap your productivity with terminal setup and command usages',
    date: '2023-04-30T00:00:00.000Z',
    tags: ['technical'],
    banner: 'https://i.ytimg.com/vi/ulEr4zSHL-c/maxresdefault.jpg',
    name: '2023-04-30-developer-productivity',
    contributors: [],
    filepath: mdImport_2023_04_30_developer_productivity,
  },
];
