name: Common setups
description: 'Sets up Node.js, Yarn, installs dependencies, and builds shared packages (common, server-common, mongo)'

runs:
  using: 'composite'
  steps:
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'yarn'

    - name: Set Yarn version to 4.8.1
      run: yarn set version 4.8.1
      shell: bash

    - name: Install dependencies
      run: yarn install --immutable
      shell: bash
