name: Common setups
description: 'Sets up Node.js, Yarn, installs dependencies, and builds shared packages (common, server-common, mongo)'

runs:
  using: 'composite'
  steps:
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'yarn'

    - name: Use latest yarn version
      run: yarn set version stable
      shell: bash

    - name: Install dependencies
      run: yarn install --immutable
      shell: bash

    - name: Build common, server-common, mongo packages
      run: yarn workspace @vtmp/common build && yarn workspace @vtmp/server-common build && yarn workspace @vtmp/mongo build
      shell: bash
