# Define a Github Actions reusable workflow
name: Build web

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Use common setups action
      uses: ./.github/actions/common-setups
    - name: Build web
      run: yarn workspace @vtmp/web build
