export enum CompanyName {
  SERVICE_NOW = 'SERVICE_NOW',
  LILLY = 'LILLY',
  MICROSOFT = 'MICROSOFT',
  MONGODB = 'MONGODB',
  BANK_OF_AMERICA = 'BANK_OF_AMERICA',
  META = 'META',
  NIANTIC = 'NIANTIC',
  ROBINHOOD = 'ROBINHOOD',
  DOORDASH = 'DOORDASH',
  LINKEDIN = 'LINKEDIN',
  PROOFPOINT = 'PROOFPOINT',
  ADOBE = 'ADOBE',
  AMAZON = 'AMAZON',
  PLAID = 'PLAID',
  WAYFAIR = 'WAYFAIR',
  GODADDY = 'GODADDY',
  MATSON_MONEY = 'MATSON_MONEY',
  SAP = 'SAP',
  HEROKU = 'HEROKU',
  MORGAN_STANLEY = 'MORGAN_STANLEY',
  SHOPIFY = 'SHOPIFY',
  MASTERCARD = 'MASTERCARD',
  SLACK = 'SLACK',
  LIBERTY_MUTUAL_INSURANCE = 'LIBERTY_MUTUAL_INSURANCE',
  HELMERICH_PAYNE = 'HELMERICH_PAYNE',
  GRAMMARLY = 'GRAMMARLY',
  BNY_MELLON = 'BNY_MELLON',
  PAYPAL = 'PAYPAL',
  GOLDMAN_SACHS = 'GOLDMAN_SACHS',
  EBAY = 'EBAY',
  VERISK = 'VERISK',
  HUBSPOT = 'HUBSPOT',
  EXPEDIA = 'EXPEDIA',
  ORACLE = 'ORACLE',
  EXPERIAN = 'EXPERIAN',
  WAYMO = 'WAYMO',
  ASANA = 'ASANA',
  MCDONALDS = 'MCDONALDS',
  BUBBLE_IO = 'BUBBLE_IO',
  KENCO_GROUP = 'KENCO_GROUP',
  COINBASE = 'COINBASE',
  FOREFLIGHT = 'FOREFLIGHT',
  QUALCOMM = 'QUALCOMM',
  PALANTIR = 'PALANTIR',
  BLOOMBERG = 'BLOOMBERG',
  GOOGLE = 'GOOGLE',
  UKG = 'UKG',
  SENTRY = 'SENTRY',
  PLAYSTATION = 'PLAYSTATION',
  RYCO = 'RYCO',
}

export enum OfferType {
  INTERNSHIP = 'INTERNSHIP',
  NEW_GRAD = 'NEW_GRAD',
}

export enum OfferChannel {
  EXTERNAL = 'EXTERNAL',
  RETURN_OFFER = 'RETURN_OFFER',
}

export enum MentorshipRole {
  PROGRAM_MANAGER = 'PROGRAM_MANAGER',
  PROGRAM_FOUNDER = 'PROGRAM_FOUNDER',
  PROGRAM_ADVISOR = 'PROGRAM_ADVISOR',
  SWE_PROGRAM_LEAD = 'SWE_PROGRAM_LEAD',
  SWE_RISING_LEAD = 'SWE_RISING_LEAD',
  SWE_LEAD = 'SWE_LEAD',
  SWE_INACTIVE_LEAD = 'SWE_INACTIVE_LEAD',
  SWE_MENTOR = 'SWE_MENTOR',
  SWE_EXMENTEE_INACTIVE_MENTOR = 'SWE_EXMENTEE_INACTIVE_MENTOR',
  SWE_EXMENTEE_MENTOR = 'SWE_EXMENTEE_MENTOR',
  SWE_EXMENTEE_LOGISTICS_SUPPORT = 'SWE_EXMENTEE_LOGISTICS_SUPPORT',
  SWE_MENTEE = 'SWE_MENTEE',
  PD_MENTOR = 'PD_MENTOR',
  PD_MENTEE = 'PD_MENTEE',
}

export enum MentorshipGroup {
  ORGANIZER = 'ORGANIZER',
  PARTICIPANT = 'PARTICIPANT',
}

export const rolePriority: Record<MentorshipRole, number> = {
  [MentorshipRole.SWE_PROGRAM_LEAD]: 1.0,
  [MentorshipRole.PROGRAM_MANAGER]: 1.1,
  [MentorshipRole.PROGRAM_FOUNDER]: 1.2,
  [MentorshipRole.PROGRAM_ADVISOR]: 1.3,
  [MentorshipRole.SWE_RISING_LEAD]: 2,
  [MentorshipRole.SWE_LEAD]: 2.1,
  [MentorshipRole.SWE_INACTIVE_LEAD]: 2.2,
  [MentorshipRole.PD_MENTOR]: 3,
  [MentorshipRole.SWE_MENTOR]: 3.1,
  [MentorshipRole.SWE_EXMENTEE_MENTOR]: 3.1,
  [MentorshipRole.SWE_EXMENTEE_INACTIVE_MENTOR]: 3.2,
  [MentorshipRole.SWE_EXMENTEE_LOGISTICS_SUPPORT]: 3.3,
  [MentorshipRole.PD_MENTEE]: 4,
  [MentorshipRole.SWE_MENTEE]: 4.1,
};

export enum MentorshipYear {
  YEAR_2023 = 'YEAR_2023',
  YEAR_2024 = 'YEAR_2024',
  YEAR_2025 = 'YEAR_2025',
}

export const yearDisplay: Record<MentorshipYear, number> = {
  [MentorshipYear.YEAR_2023]: 2023,
  [MentorshipYear.YEAR_2024]: 2024,
  [MentorshipYear.YEAR_2025]: 2025,
};

export enum StatsType {
  OFFERS = 'offers',
  INTERVIEWS = 'interviews',
  TIMELINE = 'timeline',
  LOGOS = 'logos',
}

export enum InterviewType {
  TECHNICAL_LC_CODING = 'T',
  OVERALL_BEHAVIORAL = 'B',
  PROJECT_WALKTHROUGH = 'W',
  SYSTEM_DESIGN = 'S',
  RECRUITER_SCREEN = 'R',
  HIRING_MANAGER = 'H',
  TRIVIA_CONCEPT = 'V',
  PRACTICAL_CODING = 'P',
  DEBUGGING = 'D',
  CRITICAL_THINKING = 'C',
  CODE_REVIEW = 'O',
}

export enum PeopleSortColumn {
  NAME = 'NAME',
  OFFERS_COUNT = 'OFFERS_COUNT',
  ROLE = 'ROLE',
}
