import { InterviewType, MentorshipRole } from '@vtmp/common/constants';

export const rolePriority: Record<MentorshipRole, number> = {
  [MentorshipRole.PROGRAM_LEAD]: 1.0,
  [MentorshipRole.PROGRAM_FOUNDER]: 1.1,
  [MentorshipRole.SWE_PROGRAM_LEAD]: 1.2,
  [MentorshipRole.PROGRAM_ADVISOR]: 1.3,
  [MentorshipRole.SWE_RISING_LEAD]: 2,
  [MentorshipRole.SWE_LEAD]: 2.1,
  [MentorshipRole.SWE_INACTIVE_LEAD]: 2.2,
  [MentorshipRole.PD_MENTOR]: 3,
  [MentorshipRole.SWE_MENTOR]: 3.1,
  [MentorshipRole.SWE_EXMENTEE_MENTOR]: 3.1,
  [MentorshipRole.SWE_EXMENTEE_INACTIVE_MENTOR]: 3.2,
  [MentorshipRole.SWE_EXMENTEE_LOGISTICS_SUPPORT]: 3.3,
  [MentorshipRole.PD_MENTEE]: 4,
  [MentorshipRole.SWE_MENTEE]: 4.1,
  [MentorshipRole.COMMUNITY_MEMBER]: 10,
};

export enum MentorshipYear {
  YEAR_2023 = 'YEAR_2023',
  YEAR_2024 = 'YEAR_2024',
  YEAR_2025 = 'YEAR_2025',
}

export enum StatsType {
  OFFERS = 'offers',
  INTERVIEWS = 'interviews',
  TIMELINE = 'timeline',
  LOGOS = 'logos',
}

export const interviewTypeAbbreviation: Record<InterviewType, string> = {
  [InterviewType.TECHNICAL_LC_CODING]: 'T',
  [InterviewType.OVERALL_BEHAVIORAL]: 'B',
  [InterviewType.PROJECT_WALKTHROUGH]: 'W',
  [InterviewType.SYSTEM_DESIGN]: 'S',
  [InterviewType.RECRUITER_SCREEN]: 'R',
  [InterviewType.HIRING_MANAGER]: 'H',
  [InterviewType.TRIVIA_CONCEPT]: 'V',
  [InterviewType.PRACTICAL_CODING]: 'P',
  [InterviewType.DEBUGGING]: 'D',
  [InterviewType.CRITICAL_THINKING]: 'C',
  [InterviewType.CODE_REVIEW]: 'O',
};

export enum PeopleSortColumn {
  NAME = 'NAME',
  OFFERS_COUNT = 'OFFERS_COUNT',
  ROLE = 'ROLE',
}

export enum PeopleName {
  KHOA_LE = 'KHOA_LE',
  HUY_ANH = 'HUY_ANH',
  CHAN_LE = 'CHAN_LE',
  NGUYEN_VU = 'NGUYEN_VU',
  THU_ANH = 'THU_ANH',
  KEVIN_LUU = 'KEVIN_LUU',
  JENNY_QUACH = 'JENNY_QUACH',
  THIEN_SON = 'THIEN_SON',
  NICK_DOAN = 'NICK_DOAN',
  SARAH_VO = 'SARAH_VO',
  HUU_DANG = 'HUU_DANG',
  ROBIN_HOANG = 'ROBIN_HOANG',
  PHUOC_ONG = 'PHUOC_ONG',
  KHUE_TANG = 'KHUE_TANG',
  PHUONG_CAO = 'PHUONG_CAO',
  NGOC_DOAN = 'NGOC_DOAN',
  CUONG_NGUYEN = 'CUONG_NGUYEN',
  MINH_QUAN = 'MINH_QUAN',
  TRANG_VU = 'TRANG_VU',
  HIEU_VUONG = 'HIEU_VUONG',
  THANH_NGUYEN = 'THANH_NGUYEN',
  HUNG_NGO = 'HUNG_NGO',
  NGOC_ANH_TRAN = 'NGOC_ANH_TRAN',
  VY_NGUYEN = 'VY_NGUYEN',
  VIEN_NGUYEN = 'VIEN_NGUYEN',
  THUC_ANH = 'THUC_ANH',
  GIANG_PHAM = 'GIANG_PHAM',
  PHAN_ANH = 'PHAN_ANH',
  QUY_NGUYEN = 'QUY_NGUYEN',
  THANG_NGUYEN = 'THANG_NGUYEN',
  QUYNH_TRAN = 'QUYNH_TRAN',
  PHUONG_LE = 'PHUONG_LE',
  BA_QUAN = 'BA_QUAN',
  VY_TRAN = 'VY_TRAN',
  TRANG_LINH = 'TRANG_LINH',
  PHUC_KHANG = 'PHUC_KHANG',
  LONG_DAU = 'LONG_DAU',
  HOANG_NGUYEN = 'HOANG_NGUYEN',
  HA_LINH = 'HA_LINH',
  KHANH_LINH = 'KHANH_LINH',
  HUU_KHANG = 'HUU_KHANG',
  TRANG_DO = 'TRANG_DO',
  HAI_ANH = 'HAI_ANH',
  NAM_NGUYEN = 'NAM_NGUYEN',
  TRI_HOANG = 'TRI_HOANG',
  VAN_NGUYEN = 'VAN_NGUYEN',
  KHA_TRAN = 'KHA_TRAN',
  HUE_QUAN = 'HUE_QUAN',
  TRAN_VO = 'TRAN_VO',
  DIEP_NGUYEN = 'DIEP_NGUYEN',
  MONICA_HUYNH = 'MONICA_HUYNH',
  PHUC_TRUONG = 'PHUC_TRUONG',
  AN_TRAN = 'AN_TRAN',
  QUANG_MINH = 'QUANG_MINH',
  DANG_SON = 'DANG_SON',
  NGOC_LINH = 'NGOC_LINH',
  DUC_NGUYEN = 'DUC_NGUYEN',
  XUAN_ANH = 'XUAN_ANH',
  DAT_VU = 'DAT_VU',
  CHAU_TRAN = 'CHAU_TRAN',
  TUAN_ANH = 'TUAN_ANH',
  QUYEN_DOAN = 'QUYEN_DOAN',
  NHAT_LE = 'NHAT_LE',
  DAN_NGUYEN = 'DAN_NGUYEN',
  TAM_NGUYEN = 'TAM_NGUYEN',
  THAI_DANG = 'THAI_DANG',
  NGOC_MINH = 'NGOC_MINH',
  TAM_DANG = 'TAM_DANG',
  TRI_NGUYEN = 'TRI_NGUYEN',
  UYEN_HOANG = 'UYEN_HOANG',
  KEVIN_DOAN = 'KEVIN_DOAN',
  THUY_LINH = 'THUY_LINH',
  KIEN_TRAN = 'KIEN_TRAN',
  HA_NGUYEN = 'HA_NGUYEN',
  NGOC_ANH_HOANG = 'NGOC_ANH_HOANG',
}

export enum ProjectName {
  FINANCIAL_APP = 'FINANCIAL_APP',
  SAFE_TRAVEL = 'SAFE_TRAVEL',
  PRODUCTIFY = 'PRODUCTIFY',
  FLAVORIE = 'FLAVORIE',
  PICK_ME_FOOD = 'PICK_ME_FOOD',
  GATHERING_GLOBE = 'GATHERING_GLOBE',
  BONDSCAPE = 'BONDSCAPE',
  CUPID = 'CUPID',
  PEACE_POD = 'PEACE_POD',
  TOURIFIC = 'TOURIFIC',
  SUBLEAZY = 'SUBLEAZY',
  ZERO_KM = 'ZERO_KM',
  LOCAL_TASTE = 'LOCAL_TASTE',
  CARE_BEAR = 'CARE_BEAR',
  FAIR_SHARE = 'FAIR_SHARE',
  APPLICATION_TRACKER = 'APPLICATION_TRACKER',
  CODE_BUDDY = 'CODE_BUDDY',
}

export enum QueryKey {
  SUBMIT_LINK = '/api/links',
  GET_APPLICATIONS = '/api/applications',
  GET_APPLICATIONS_COUNT_BY_STATUS = '/api/applications/countByStatus',
}

export enum Method {
  GET = 'GET',
  POST = 'POST',
  PUT = 'PUT',
  DELETE = 'DELETE',
}
