import {
  InterviewType,
  MentorshipRole,
  ApplicationStatus,
  InvitationStatus,
  LinkStatus,
} from '@vtmp/common/constants';

export const rolePriority: Record<MentorshipRole, number> = {
  [MentorshipRole.PROGRAM_LEAD]: 1.0,
  [MentorshipRole.PROGRAM_FOUNDER]: 1.1,
  [MentorshipRole.SWE_PROGRAM_LEAD]: 1.2,
  [MentorshipRole.PROGRAM_ADVISOR]: 1.3,
  [MentorshipRole.SWE_RISING_LEAD]: 2,
  [MentorshipRole.SWE_LEAD]: 2.1,
  [MentorshipRole.SWE_INACTIVE_LEAD]: 2.2,
  [MentorshipRole.PD_MENTOR]: 3,
  [MentorshipRole.SWE_MENTOR]: 3.1,
  [MentorshipRole.SWE_EXMENTEE_MENTOR]: 3.1,
  [MentorshipRole.SWE_EXMENTEE_INACTIVE_MENTOR]: 3.2,
  [MentorshipRole.SWE_EXMENTEE_LOGISTICS_SUPPORT]: 3.3,
  [MentorshipRole.PD_MENTEE]: 4,
  [MentorshipRole.SWE_MENTEE]: 4.1,
  [MentorshipRole.COMMUNITY_MEMBER]: 10,
};

export enum MentorshipYear {
  YEAR_2023 = 'YEAR_2023',
  YEAR_2024 = 'YEAR_2024',
  YEAR_2025 = 'YEAR_2025',
}

export enum StatsType {
  INTERVIEWS = 'INTERVIEWS',
LOGOS = 'LOGOS',
OFFERS = 'OFFERS',
TIMELINE = 'TIMELINE',
}

export const interviewTypeAbbreviation: Record<InterviewType, string> = {
  [InterviewType.TECHNICAL_LC_CODING]: 'T',
  [InterviewType.OVERALL_BEHAVIORAL]: 'B',
  [InterviewType.PROJECT_WALKTHROUGH]: 'W',
  [InterviewType.SYSTEM_DESIGN]: 'S',
  [InterviewType.RECRUITER_SCREEN]: 'R',
  [InterviewType.HIRING_MANAGER]: 'H',
  [InterviewType.TRIVIA_CONCEPT]: 'V',
  [InterviewType.PRACTICAL_CODING]: 'P',
  [InterviewType.DEBUGGING]: 'D',
  [InterviewType.CRITICAL_THINKING]: 'C',
  [InterviewType.CODE_REVIEW]: 'O',
};

export enum PeopleSortColumn {
  NAME = 'NAME',
  OFFERS_COUNT = 'OFFERS_COUNT',
  ROLE = 'ROLE',
}

export enum PeopleName {
  AN_TRAN = 'AN_TRAN',
BA_QUAN = 'BA_QUAN',
CHAN_LE = 'CHAN_LE',
CHAU_TRAN = 'CHAU_TRAN',
CUONG_NGUYEN = 'CUONG_NGUYEN',
DAN_NGUYEN = 'DAN_NGUYEN',
DANG_SON = 'DANG_SON',
DAT_VU = 'DAT_VU',
DIEP_NGUYEN = 'DIEP_NGUYEN',
DUC_NGUYEN = 'DUC_NGUYEN',
GIANG_PHAM = 'GIANG_PHAM',
HA_LINH = 'HA_LINH',
HA_NGUYEN = 'HA_NGUYEN',
HAI_ANH = 'HAI_ANH',
HIEU_VUONG = 'HIEU_VUONG',
HOANG_NGUYEN = 'HOANG_NGUYEN',
HUE_QUAN = 'HUE_QUAN',
HUNG_NGO = 'HUNG_NGO',
HUU_DANG = 'HUU_DANG',
HUU_KHANG = 'HUU_KHANG',
HUY_ANH = 'HUY_ANH',
JENNY_QUACH = 'JENNY_QUACH',
KEVIN_DOAN = 'KEVIN_DOAN',
KEVIN_LUU = 'KEVIN_LUU',
KHA_TRAN = 'KHA_TRAN',
KHANH_LINH = 'KHANH_LINH',
KHOA_LE = 'KHOA_LE',
KHUE_TANG = 'KHUE_TANG',
KIEN_TRAN = 'KIEN_TRAN',
LONG_DAU = 'LONG_DAU',
MINH_QUAN = 'MINH_QUAN',
MONICA_HUYNH = 'MONICA_HUYNH',
NAM_NGUYEN = 'NAM_NGUYEN',
NGOC_ANH_HOANG = 'NGOC_ANH_HOANG',
NGOC_ANH_TRAN = 'NGOC_ANH_TRAN',
NGOC_DOAN = 'NGOC_DOAN',
NGOC_LINH = 'NGOC_LINH',
NGOC_MINH = 'NGOC_MINH',
NGUYEN_VU = 'NGUYEN_VU',
NHAT_LE = 'NHAT_LE',
NICK_DOAN = 'NICK_DOAN',
PHAN_ANH = 'PHAN_ANH',
PHUC_KHANG = 'PHUC_KHANG',
PHUC_TRUONG = 'PHUC_TRUONG',
PHUOC_ONG = 'PHUOC_ONG',
PHUONG_CAO = 'PHUONG_CAO',
PHUONG_LE = 'PHUONG_LE',
QUANG_MINH = 'QUANG_MINH',
QUY_NGUYEN = 'QUY_NGUYEN',
QUYEN_DOAN = 'QUYEN_DOAN',
QUYNH_TRAN = 'QUYNH_TRAN',
ROBIN_HOANG = 'ROBIN_HOANG',
SARAH_VO = 'SARAH_VO',
TAM_DANG = 'TAM_DANG',
TAM_NGUYEN = 'TAM_NGUYEN',
THAI_DANG = 'THAI_DANG',
THANG_NGUYEN = 'THANG_NGUYEN',
THANH_NGUYEN = 'THANH_NGUYEN',
THIEN_SON = 'THIEN_SON',
THU_ANH = 'THU_ANH',
THUC_ANH = 'THUC_ANH',
THUY_LINH = 'THUY_LINH',
TRAN_VO = 'TRAN_VO',
TRANG_DO = 'TRANG_DO',
TRANG_LINH = 'TRANG_LINH',
TRANG_VU = 'TRANG_VU',
TRI_HOANG = 'TRI_HOANG',
TRI_NGUYEN = 'TRI_NGUYEN',
TUAN_ANH = 'TUAN_ANH',
UYEN_HOANG = 'UYEN_HOANG',
VAN_NGUYEN = 'VAN_NGUYEN',
VIEN_NGUYEN = 'VIEN_NGUYEN',
VY_NGUYEN = 'VY_NGUYEN',
VY_TRAN = 'VY_TRAN',
XUAN_ANH = 'XUAN_ANH',
}

export enum ProjectName {
  APPLICATION_TRACKER = 'APPLICATION_TRACKER',
BONDSCAPE = 'BONDSCAPE',
CARE_BEAR = 'CARE_BEAR',
CODE_BUDDY = 'CODE_BUDDY',
CUPID = 'CUPID',
FAIR_SHARE = 'FAIR_SHARE',
FINANCIAL_APP = 'FINANCIAL_APP',
FLAVORIE = 'FLAVORIE',
GATHERING_GLOBE = 'GATHERING_GLOBE',
LOCAL_TASTE = 'LOCAL_TASTE',
PEACE_POD = 'PEACE_POD',
PICK_ME_FOOD = 'PICK_ME_FOOD',
PRODUCTIFY = 'PRODUCTIFY',
SAFE_TRAVEL = 'SAFE_TRAVEL',
SUBLEAZY = 'SUBLEAZY',
TOURIFIC = 'TOURIFIC',
ZERO_KM = 'ZERO_KM',
}

export enum QueryKey {
  GET_APPLICATION_BY_ID = 'GET_APPLICATION_BY_ID',
GET_APPLICATIONS = 'GET_APPLICATIONS',
GET_APPLICATIONS_COUNT_BY_STATUS = 'GET_APPLICATIONS_COUNT_BY_STATUS',
GET_INTERVIEW_BY_APPLICATION_ID = 'GET_INTERVIEW_BY_APPLICATION_ID',
GET_JOB_POSTINGS = 'GET_JOB_POSTINGS',
GET_JOB_POSTINGS_IN_ADAY = 'GET_JOB_POSTINGS_IN_ADAY',
GET_LINKS = 'GET_LINKS',
GET_LINKS_COUNT_BY_STATUS = 'GET_LINKS_COUNT_BY_STATUS',
SUBMIT_LINK = 'SUBMIT_LINK',
}

export enum Method {
  DELETE = 'DELETE',
GET = 'GET',
POST = 'POST',
PUT = 'PUT',
}

export const StatusToColorMapping: Record<
  ApplicationStatus | LinkStatus,
  string
> = {
  [ApplicationStatus.SUBMITTED]: 'bg-[#A2BFF0]',
  [ApplicationStatus.OA]: 'bg-[#F49DFF]',
  [ApplicationStatus.INTERVIEWING]: 'bg-[#F8FF6A]',
  [ApplicationStatus.OFFERED]: 'bg-[#A3F890]',
  [ApplicationStatus.WITHDRAWN]: 'bg-[#CAAB94]',
  [ApplicationStatus.REJECTED]: 'bg-[#FEB584]',
  [LinkStatus.PENDING]: 'bg-[#A2BFF0]',
  [LinkStatus.APPROVED]: 'bg-[#A3F890]',
};

export const InvitationStatusToColorMapping: Record<InvitationStatus, string> =
  {
    [InvitationStatus.ACCEPTED]: 'bg-(--vtmp-green)',
    [InvitationStatus.EXPIRED]: 'bg-(--vtmp-brown)',
    [InvitationStatus.PENDING]: 'bg-(--vtmp-yellow)',
    [InvitationStatus.REVOKED]: 'bg-(--vtmp-orange)',
  };
export const MIN_PASSWORD_LENGTH = 8;
export const MAX_PASSWORD_LENGTH = 20;
