name: Test web
description: 'Runs tests for the web workspace and uploads coverage to Codecov'

inputs:
  CODECOV_TOKEN:
    description: 'A Github PAT'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Run tests and collect coverage
      run: yarn workspace @vtmp/web coverage
      shell: bash

    - name: Upload results to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ inputs.CODECOV_TOKEN }}
