export enum ApplicationStatus {
  INTERVIEWING = 'INTERVIEWING',
OA = 'OA',
OFFERED = 'OFFERED',
REJECTED = 'REJECTED',
SUBMITTED = 'SUBMITTED',
WITHDRAWN = 'WITHDRAWN',
}

export enum InterviewType {
  CODE_REVIEW = 'CODE_REVIEW',
CRITICAL_THINKING = 'CRITICAL_THINKING',
DEBUGGING = 'DEBUGGING',
HIRING_MANAGER = 'HIRING_MANAGER',
OVERALL_BEHAVIORAL = 'OVERALL_BEHAVIORAL',
PRACTICAL_CODING = 'PRACTICAL_CODING',
PROJECT_WALKTHROUGH = 'PROJECT_WALKTHROUGH',
RECRUITER_SCREEN = 'RECRUITER_SCREEN',
SYSTEM_DESIGN = 'SYSTEM_DESIGN',
TECHNICAL_LC_CODING = 'TECHNICAL_LC_CODING',
TRIVIA_CONCEPT = 'TRIVIA_CONCEPT',
}

export enum InterviewStatus {
  FAILED = 'FAILED',
PASSED = 'PASSED',
PENDING = 'PENDING',
UPCOMING = 'UPCOMING',
WITHDRAWN = 'WITHDRAWN',
}

export enum InvitationStatus {
  ACCEPTED = 'ACCEPTED',
  EXPIRED = 'EXPIRED',
  PENDING = 'PENDING',
  REVOKED = 'REVOKED',
}

export enum JobPostingRegion {
  CANADA = 'CANADA',
US = 'US',
}

export enum LinkStatus {
  APPROVED = 'APPROVED',
PENDING = 'PENDING',
REJECTED = 'REJECTED',
}

export enum SystemRole {
  ADMIN = 'ADMIN',
MODERATOR = 'MODERATOR',
SERVICE = 'SERVICE',
USER = 'USER',
}

export enum Permission {
  CREATE_JOB_LINK = 'CREATE_JOB_LINK',
MANAGE_APPLICATION = 'MANAGE_APPLICATION',
MANAGE_INTERVIEW = 'MANAGE_INTERVIEW',
MANAGE_INVITATION = 'MANAGE_INVITATION',
MANAGE_JOB_LINK = 'MANAGE_JOB_LINK',
MANAGE_JOB_POSTING = 'MANAGE_JOB_POSTING',
VIEW_ALL_DATA = 'VIEW_ALL_DATA',
VIEW_APPLICATION = 'VIEW_APPLICATION',
VIEW_INTERVIEW = 'VIEW_INTERVIEW',
VIEW_INVITATION = 'VIEW_INVITATION',
VIEW_JOB_LINK = 'VIEW_JOB_LINK',
VIEW_JOB_POSTING = 'VIEW_JOB_POSTING',
}

export enum InterestLevel {
  HIGH = 'HIGH',
LOW = 'LOW',
MEDIUM = 'MEDIUM',
}

export enum CompanyName {
  ADOBE = 'ADOBE',
AMAZON = 'AMAZON',
ASANA = 'ASANA',
BANK_OF_AMERICA = 'BANK_OF_AMERICA',
BLOOMBERG = 'BLOOMBERG',
BNY_MELLON = 'BNY_MELLON',
BUBBLE_IO = 'BUBBLE_IO',
COINBASE = 'COINBASE',
DOORDASH = 'DOORDASH',
EBAY = 'EBAY',
EXPEDIA = 'EXPEDIA',
EXPERIAN = 'EXPERIAN',
FOREFLIGHT = 'FOREFLIGHT',
G_RESEARCH = 'G_RESEARCH',
GODADDY = 'GODADDY',
GOLDMAN_SACHS = 'GOLDMAN_SACHS',
GOOGLE = 'GOOGLE',
GRAMMARLY = 'GRAMMARLY',
HEALTH_ENHANCEMENT_SYSTEMS = 'HEALTH_ENHANCEMENT_SYSTEMS',
HELMERICH_PAYNE = 'HELMERICH_PAYNE',
HEROKU = 'HEROKU',
HIGHMARK_HEALTH = 'HIGHMARK_HEALTH',
HUBSPOT = 'HUBSPOT',
KENCO_GROUP = 'KENCO_GROUP',
LIBERTY_MUTUAL_INSURANCE = 'LIBERTY_MUTUAL_INSURANCE',
LILLY = 'LILLY',
LINKEDIN = 'LINKEDIN',
MASTERCARD = 'MASTERCARD',
MATSON_MONEY = 'MATSON_MONEY',
MCDONALDS = 'MCDONALDS',
META = 'META',
MICROSOFT = 'MICROSOFT',
MONGODB = 'MONGODB',
MORGAN_STANLEY = 'MORGAN_STANLEY',
NIANTIC = 'NIANTIC',
NVIDIA = 'NVIDIA',
ORACLE = 'ORACLE',
PALANTIR = 'PALANTIR',
PAYPAL = 'PAYPAL',
PLAID = 'PLAID',
PLAYSTATION = 'PLAYSTATION',
PROOFPOINT = 'PROOFPOINT',
QUALCOMM = 'QUALCOMM',
ROBINHOOD = 'ROBINHOOD',
RYCO = 'RYCO',
SAP = 'SAP',
SENTRY = 'SENTRY',
SERVICE_NOW = 'SERVICE_NOW',
SHOPIFY = 'SHOPIFY',
SLACK = 'SLACK',
SLB = 'SLB',
UKG = 'UKG',
VERISK = 'VERISK',
WAYFAIR = 'WAYFAIR',
WAYMO = 'WAYMO',
}

export enum OfferType {
  INTERNSHIP = 'INTERNSHIP',
  NEW_GRAD = 'NEW_GRAD',
}

export enum OfferChannel {
  EXTERNAL = 'EXTERNAL',
  RETURN_OFFER = 'RETURN_OFFER',
}

export enum MentorshipRole {
  COMMUNITY_MEMBER = 'COMMUNITY_MEMBER',
PD_MENTEE = 'PD_MENTEE',
PD_MENTOR = 'PD_MENTOR',
PROGRAM_ADVISOR = 'PROGRAM_ADVISOR',
PROGRAM_FOUNDER = 'PROGRAM_FOUNDER',
PROGRAM_LEAD = 'PROGRAM_LEAD',
SWE_EXMENTEE_INACTIVE_MENTOR = 'SWE_EXMENTEE_INACTIVE_MENTOR',
SWE_EXMENTEE_LOGISTICS_SUPPORT = 'SWE_EXMENTEE_LOGISTICS_SUPPORT',
SWE_EXMENTEE_MENTOR = 'SWE_EXMENTEE_MENTOR',
SWE_INACTIVE_LEAD = 'SWE_INACTIVE_LEAD',
SWE_LEAD = 'SWE_LEAD',
SWE_MENTEE = 'SWE_MENTEE',
SWE_MENTOR = 'SWE_MENTOR',
SWE_PROGRAM_LEAD = 'SWE_PROGRAM_LEAD',
SWE_RISING_LEAD = 'SWE_RISING_LEAD',
}

export enum MentorshipGroup {
  ORGANIZER = 'ORGANIZER',
  PARTICIPANT = 'PARTICIPANT',
}

export enum StatsType {
  INTERVIEWS = 'INTERVIEWS',
LOGOS = 'LOGOS',
OFFERS = 'OFFERS',
TIMELINE = 'TIMELINE',
}

export enum ProgramRole {
  PD_MENTEE = 'PD_MENTEE',
PD_MENTOR = 'PD_MENTOR',
PROGRAM_ADVISOR = 'PROGRAM_ADVISOR',
PROGRAM_FOUNDER = 'PROGRAM_FOUNDER',
PROGRAM_MANAGER = 'PROGRAM_MANAGER',
SWE_EXMENTEE_INACTIVE_MENTOR = 'SWE_EXMENTEE_INACTIVE_MENTOR',
SWE_EXMENTEE_LOGISTICS_SUPPORT = 'SWE_EXMENTEE_LOGISTICS_SUPPORT',
SWE_EXMENTEE_MENTOR = 'SWE_EXMENTEE_MENTOR',
SWE_INACTIVE_LEAD = 'SWE_INACTIVE_LEAD',
SWE_LEAD = 'SWE_LEAD',
SWE_MENTEE = 'SWE_MENTEE',
SWE_MENTOR = 'SWE_MENTOR',
SWE_PROGRAM_LEAD = 'SWE_PROGRAM_LEAD',
SWE_RISING_LEAD = 'SWE_RISING_LEAD',
}

export enum Department {
  PD = 'PD',
SWE = 'SWE',
}

export enum JobTitle {
  DATA_ENGINEER = 'DATA_ENGINEER',
DATA_SCIENTIST = 'DATA_SCIENTIST',
PRODUCT_DESIGNER = 'PRODUCT_DESIGNER',
SOFTWARE_ENGINEER = 'SOFTWARE_ENGINEER',
}

export enum JobFunction {
  DATA_ENGINEER = 'DATA_ENGINEER',
DATA_SCIENTIST = 'DATA_SCIENTIST',
PRODUCT_DESIGNER = 'PRODUCT_DESIGNER',
SOFTWARE_ENGINEER = 'SOFTWARE_ENGINEER',
}

export enum JobType {
  INDUSTRY = 'INDUSTRY',
INTERNSHIP = 'INTERNSHIP',
NEW_GRAD = 'NEW_GRAD',
}
