export enum ApplicationStatus {
  INTERVIEWING = 'INTERVIEWING',
  OA = 'OA',
  OFFERED = 'OFFERED',
  REJECTED = 'REJECTED',
  SUBMITTED = 'SUBMITTED',
  WITHDRAWN = 'WITHDRAWN',
}

export enum InterviewType {
  CODE_REVIEW = 'CODE_REVIEW',
  CRITICAL_THINKING = 'CRITICAL_THINKING',
  DEBUGGING = 'DEBUGGING',
  HIRING_MANAGER = 'HIRING_MANAGER',
  OVERALL_BEHAVIORAL = 'OVERALL_BEHAVIORAL',
  PRACTICAL_CODING = 'PRACTICAL_CODING',
  PROJECT_WALKTHROUGH = 'PROJECT_WALKTHROUGH',
  RECRUITER_SCREEN = 'RECRUITER_SCREEN',
  SYSTEM_DESIGN = 'SYSTEM_DESIGN',
  TECHNICAL_LC_CODING = 'TECHNICAL_LC_CODING',
  TRIVIA_CONCEPT = 'TRIVIA_CONCEPT',
}

export enum InterviewStatus {
  FAILED = 'FAILED',
  PASSED = 'PASSED',
  PENDING = 'PENDING',
  UPCOMING = 'UPCOMING',
  WITHDRAWN = 'WITHDRAWN',
}

export enum InterviewShareStatus {
  SHARED_ANONYMOUS = 'SHARED_ANONYMOUS',
  SHARED_PUBLIC = 'SHARED_PUBLIC',
  UNSHARED = 'UNSHARED',
}

export enum InvitationStatus {
  ACCEPTED = 'ACCEPTED',
  EXPIRED = 'EXPIRED',
  PENDING = 'PENDING',
  REVOKED = 'REVOKED',
}

export enum JobPostingRegion {
  CANADA = 'CANADA',
  US = 'US',
}

export enum LinkRegion {
  CANADA = 'CANADA',
  UNKNOWN = 'UNKNOWN',
  US = 'US',
}

export enum SystemRole {
  ADMIN = 'ADMIN',
  MODERATOR = 'MODERATOR',
  SERVICE = 'SERVICE',
  USER = 'USER',
}

export enum Permission {
  CREATE_JOB_LINK = 'CREATE_JOB_LINK',
  MANAGE_APPLICATION = 'MANAGE_APPLICATION',
  MANAGE_INTERVIEW = 'MANAGE_INTERVIEW',

  MANAGE_INVITATION = 'MANAGE_INVITATION',
  MANAGE_JOB_LINK = 'MANAGE_JOB_LINK',

  MANAGE_JOB_POSTING = 'MANAGE_JOB_POSTING',
  VIEW_ALL_DATA = 'VIEW_ALL_DATA',

  VIEW_APPLICATION = 'VIEW_APPLICATION',
  VIEW_INTERVIEW = 'VIEW_INTERVIEW',

  VIEW_INVITATION = 'VIEW_INVITATION',
  VIEW_JOB_LINK = 'VIEW_JOB_LINK',
  VIEW_JOB_POSTING = 'VIEW_JOB_POSTING',

  VIEW_VISUALIZATION = 'VIEW_VISUALIZATION',
}

export enum InterestLevel {
  HIGH = 'HIGH',
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
}

export enum CompanyName {
  ADOBE = 'ADOBE',
  AMAZON = 'AMAZON',
  ARISTA = 'ARISTA',
  ASANA = 'ASANA',
  AUTODESK = 'AUTODESK',
  BANK_OF_AMERICA = 'BANK_OF_AMERICA',
  BLOCK = 'BLOCK',
  BLOOMBERG = 'BLOOMBERG',
  BNY_MELLON = 'BNY_MELLON',
  BUBBLE_IO = 'BUBBLE_IO',
  CAPITAL_ONE = 'CAPITAL_ONE',
  COINBASE = 'COINBASE',
  COSTAR = 'COSTAR',
  DATABRICKS = 'DATABRICKS',
  DOORDASH = 'DOORDASH',
  DUOLINGO = 'DUOLINGO',
  EBAY = 'EBAY',
  EXPEDIA = 'EXPEDIA',
  EXPERIAN = 'EXPERIAN',
  FLEXCAR = 'FLEXCAR',
  FOREFLIGHT = 'FOREFLIGHT',
  GODADDY = 'GODADDY',
  GOLDMAN_SACHS = 'GOLDMAN_SACHS',
  GOOGLE = 'GOOGLE',
  GRACE_TECHNOLOGIES = 'GRACE_TECHNOLOGIES',
  GRAMMARLY = 'GRAMMARLY',
  G_RESEARCH = 'G_RESEARCH',
  HEALTH_ENHANCEMENT_SYSTEMS = 'HEALTH_ENHANCEMENT_SYSTEMS',
  HELMERICH_PAYNE = 'HELMERICH_PAYNE',
  HEROKU = 'HEROKU',
  HIGHMARK_HEALTH = 'HIGHMARK_HEALTH',
  HUBSPOT = 'HUBSPOT',
  INTACT = 'INTACT',
  KENCO_GROUP = 'KENCO_GROUP',
  KINGLAND = 'KINGLAND',
  LIBERTY_MUTUAL_INSURANCE = 'LIBERTY_MUTUAL_INSURANCE',
  LILLY = 'LILLY',
  LINKEDIN = 'LINKEDIN',
  LOVEPOP = 'LOVEPOP',
  MASTERCARD = 'MASTERCARD',
  MATSON_MONEY = 'MATSON_MONEY',
  MCDONALDS = 'MCDONALDS',
  META = 'META',
  MICROSOFT = 'MICROSOFT',
  MONGODB = 'MONGODB',
  MORGAN_STANLEY = 'MORGAN_STANLEY',
  NIANTIC = 'NIANTIC',
  NVIDIA = 'NVIDIA',
  ORACLE = 'ORACLE',
  PALANTIR = 'PALANTIR',
  PARSONS = 'PARSONS',
  PAYPAL = 'PAYPAL',
  PLAID = 'PLAID',
  PLAYSTATION = 'PLAYSTATION',
  PONDER = 'PONDER',
  PROOFPOINT = 'PROOFPOINT',
  QUALCOMM = 'QUALCOMM',
  RIPPLING = 'RIPPLING',
  ROBINHOOD = 'ROBINHOOD',
  RYCO = 'RYCO',
  SALESFORCE = 'SALESFORCE',
  SAP = 'SAP',
  SEMGREP = 'SEMGREP',
  SENTRY = 'SENTRY',
  SERVICENOW = 'SERVICENOW',
  SHOPIFY = 'SHOPIFY',
  SLACK = 'SLACK',
  SLB = 'SLB',
  STRIPE = 'STRIPE',
  SYNOPSYS = 'SYNOPSYS',
  TESLA = 'TESLA',
  TIKTOK = 'TIKTOK',
  TWO_SIGMA = 'TWO_SIGMA',
  UKG = 'UKG',
  VALON = 'VALON',
  VERISK = 'VERISK',
  VIASAT = 'VIASAT',
  WAYFAIR = 'WAYFAIR',
  WAYMO = 'WAYMO',
  ZIPRECRUITER = 'ZIPRECRUITER',
}

export enum OfferType {
  INTERNSHIP = 'INTERNSHIP',
  NEW_GRAD = 'NEW_GRAD',
}

export enum OfferChannel {
  EXTERNAL = 'EXTERNAL',
  RETURN_OFFER = 'RETURN_OFFER',
}

export enum MentorshipRole {
  COMMUNITY_MEMBER = 'COMMUNITY_MEMBER',
  PD_MENTEE = 'PD_MENTEE',
  PD_MENTOR = 'PD_MENTOR',
  PROGRAM_ADVISOR = 'PROGRAM_ADVISOR',
  PROGRAM_FOUNDER = 'PROGRAM_FOUNDER',
  PROGRAM_LEAD = 'PROGRAM_LEAD',
  SWE_EXMENTEE_INACTIVE_MENTOR = 'SWE_EXMENTEE_INACTIVE_MENTOR',
  SWE_EXMENTEE_LOGISTICS_SUPPORT = 'SWE_EXMENTEE_LOGISTICS_SUPPORT',
  SWE_EXMENTEE_MENTOR = 'SWE_EXMENTEE_MENTOR',
  SWE_INACTIVE_LEAD = 'SWE_INACTIVE_LEAD',
  SWE_LEAD = 'SWE_LEAD',
  SWE_MENTEE = 'SWE_MENTEE',
  SWE_MENTOR = 'SWE_MENTOR',
  SWE_PROGRAM_LEAD = 'SWE_PROGRAM_LEAD',
  SWE_RISING_LEAD = 'SWE_RISING_LEAD',
}

export enum MentorshipGroup {
  ORGANIZER = 'ORGANIZER',
  PARTICIPANT = 'PARTICIPANT',
}

export enum StatsType {
  INTERVIEWS = 'INTERVIEWS',
  LOGOS = 'LOGOS',
  OFFERS = 'OFFERS',
  TIMELINE = 'TIMELINE',
}

export enum JobFunction {
  DATA_ENGINEER = 'DATA_ENGINEER',
  DATA_SCIENTIST = 'DATA_SCIENTIST',
  PRODUCT_DESIGNER = 'PRODUCT_DESIGNER',
  SOFTWARE_ENGINEER = 'SOFTWARE_ENGINEER',
  UNKNOWN = 'UNKNOWN',
}

export enum JobType {
  INDUSTRY = 'INDUSTRY',
  INTERNSHIP = 'INTERNSHIP',
  NEW_GRAD = 'NEW_GRAD',
  UNKNOWN = 'UNKNOWN',
}

export enum LinkStatus {
  // admin manually approved link
  ADMIN_APPROVED = 'ADMIN_APPROVED',
  // admin manually rejected link
  ADMIN_REJECTED = 'ADMIN_REJECTED',
  // link finished processing successfully, pending manual review.
  PENDING_ADMIN_REVIEW = 'PENDING_ADMIN_REVIEW',
  // ---- MUST NOT CONTAIN LinkProcessingFailureStage ----
  // New links to process.
  PENDING_PROCESSING = 'PENDING_PROCESSING',

  // ---- MUST CONTAIN LinkProcessingFailureStage ----
  // Links to retry after failing any processing stage
  PENDING_RETRY = 'PENDING_RETRY',
  // failed to process link even after retry (ex: attempsCount > 4). Manual intervention needed (e.g. 403 Forbidden)
  PIPELINE_FAILED = 'PIPELINE_FAILED',
  // when link should no longer be processed (e.g. virus link), abandon any long retry
  PIPELINE_REJECTED = 'PIPELINE_REJECTED',
}

export enum LinkProcessingFailureStage {
  EXTRACTION_FAILED = 'EXTRACTION_FAILED',
  PRE_VALIDATION_FAILED = 'PRE_VALIDATION_FAILED',
  SCRAPING_FAILED = 'SCRAPING_FAILED',
  UNKNOWN_FAILED = 'UNKNOWN_FAILED',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  VIRUS_FAILED = 'VIRUS_FAILED',
}
