export enum ApplicationStatus {
  SUBMITTED = 'SUBMITTED',
  OA = 'OA',
  INTERVIEWING = 'INTERVIEWING',
  OFFERED = 'OFFERED',
  REJECTED = 'REJECTED',
  WITHDRAWN = 'WITHDRAWN',
}

export enum InterviewType {
  CRITICAL_THINKING = 'CRITICAL_THINKING',
  CODE_REVIEW = 'CODE_REVIEW',
  TECHNICAL_LC_CODING = 'TECHNICAL_LC_CODING',
  OVERALL_BEHAVIORAL = 'OVERALL_BEHAVIORAL',
  PROJECT_WALKTHROUGH = 'PROJECT_WALKTHROUGH',
  SYSTEM_DESIGN = 'SYSTEM_DESIGN',
  RECRUITER_SCREEN = 'RECRUITER_SCREEN',
  HIRING_MANAGER = 'HIRING_MANAGER',
  TRIVIA_CONCEPT = 'TRIVIA_CONCEPT',
  PRACTICAL_CODING = 'PRACTICAL_CODING',
  DEBUGGING = 'DEBUGGING',
}

export enum InterviewStatus {
  PASSED = 'PASSED',
  FAILED = 'FAILED',
  WITHDRAWN = 'WITHDRAWN',
  UPCOMING = 'UPCOMING',
  PENDING = 'PENDING',
}

export enum InvitationStatus {
  ACCEPTED = 'ACCEPTED',
  EXPIRED = 'EXPIRED',
  PENDING = 'PENDING',
  REVOKED = 'REVOKED',
}

export enum JobPostingRegion {
  US = 'US',
  CANADA = 'CANADA',
}

export enum LinkRegion {
  US = 'US',
  CANADA = 'CANADA',
  OTHER = 'OTHER',
}

export enum LinkStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum UserRole {
  ADMIN = 'ADMIN',
  MODERATOR = 'MODERATOR',
  USER = 'USER',
}

export enum Permission {
  VIEW_JOB_LINK = 'VIEW_JOB_LINK',
  CREATE_JOB_LINK = 'CREATE_JOB_LINK',
  MANAGE_JOB_LINK = 'MANAGE_JOB_LINK',

  VIEW_JOB_POSTING = 'VIEW_JOB_POSTING',
  MANAGE_JOB_POSTING = 'MANAGE_JOB_POSTING',

  VIEW_INVITATION = 'VIEW_INVITATION',
  MANAGE_INVITATION = 'MANAGE_INVITATION',

  VIEW_APPLICATION = 'VIEW_APPLICATION',
  MANAGE_APPLICATION = 'MANAGE_APPLICATION',

  VIEW_INTERVIEW = 'VIEW_INTERVIEW',
  VIEW_ALL_DATA = 'VIEW_ALL_DATA',
  MANAGE_INTERVIEW = 'MANAGE_INTERVIEW',
}

export enum InterestLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
}

export enum CompanyName {
  SERVICE_NOW = 'SERVICE_NOW',
  LILLY = 'LILLY',
  MICROSOFT = 'MICROSOFT',
  MONGODB = 'MONGODB',
  BANK_OF_AMERICA = 'BANK_OF_AMERICA',
  META = 'META',
  NIANTIC = 'NIANTIC',
  ROBINHOOD = 'ROBINHOOD',
  DOORDASH = 'DOORDASH',
  LINKEDIN = 'LINKEDIN',
  PROOFPOINT = 'PROOFPOINT',
  ADOBE = 'ADOBE',
  AMAZON = 'AMAZON',
  PLAID = 'PLAID',
  WAYFAIR = 'WAYFAIR',
  GODADDY = 'GODADDY',
  MATSON_MONEY = 'MATSON_MONEY',
  SAP = 'SAP',
  HEROKU = 'HEROKU',
  MORGAN_STANLEY = 'MORGAN_STANLEY',
  SHOPIFY = 'SHOPIFY',
  MASTERCARD = 'MASTERCARD',
  SLACK = 'SLACK',
  LIBERTY_MUTUAL_INSURANCE = 'LIBERTY_MUTUAL_INSURANCE',
  HELMERICH_PAYNE = 'HELMERICH_PAYNE',
  GRAMMARLY = 'GRAMMARLY',
  BNY_MELLON = 'BNY_MELLON',
  PAYPAL = 'PAYPAL',
  GOLDMAN_SACHS = 'GOLDMAN_SACHS',
  EBAY = 'EBAY',
  VERISK = 'VERISK',
  HUBSPOT = 'HUBSPOT',
  EXPEDIA = 'EXPEDIA',
  ORACLE = 'ORACLE',
  EXPERIAN = 'EXPERIAN',
  WAYMO = 'WAYMO',
  ASANA = 'ASANA',
  MCDONALDS = 'MCDONALDS',
  BUBBLE_IO = 'BUBBLE_IO',
  KENCO_GROUP = 'KENCO_GROUP',
  COINBASE = 'COINBASE',
  FOREFLIGHT = 'FOREFLIGHT',
  QUALCOMM = 'QUALCOMM',
  PALANTIR = 'PALANTIR',
  BLOOMBERG = 'BLOOMBERG',
  GOOGLE = 'GOOGLE',
  UKG = 'UKG',
  SENTRY = 'SENTRY',
  PLAYSTATION = 'PLAYSTATION',
  RYCO = 'RYCO',
  NVIDIA = 'NVIDIA',
  HIGHMARK_HEALTH = 'HIGHMARK_HEALTH',
  HEALTH_ENHANCEMENT_SYSTEMS = 'HEALTH_ENHANCEMENT_SYSTEMS',
  SLB = 'SLB',
  G_RESEARCH = 'G_RESEARCH',
}

export enum OfferType {
  INTERNSHIP = 'INTERNSHIP',
  NEW_GRAD = 'NEW_GRAD',
}

export enum OfferChannel {
  EXTERNAL = 'EXTERNAL',
  RETURN_OFFER = 'RETURN_OFFER',
}

export enum MentorshipRole {
  PROGRAM_LEAD = 'PROGRAM_LEAD',
  PROGRAM_FOUNDER = 'PROGRAM_FOUNDER',
  PROGRAM_ADVISOR = 'PROGRAM_ADVISOR',
  SWE_PROGRAM_LEAD = 'SWE_PROGRAM_LEAD',
  SWE_RISING_LEAD = 'SWE_RISING_LEAD',
  SWE_LEAD = 'SWE_LEAD',
  SWE_INACTIVE_LEAD = 'SWE_INACTIVE_LEAD',
  SWE_MENTOR = 'SWE_MENTOR',
  SWE_EXMENTEE_INACTIVE_MENTOR = 'SWE_EXMENTEE_INACTIVE_MENTOR',
  SWE_EXMENTEE_MENTOR = 'SWE_EXMENTEE_MENTOR',
  SWE_EXMENTEE_LOGISTICS_SUPPORT = 'SWE_EXMENTEE_LOGISTICS_SUPPORT',
  SWE_MENTEE = 'SWE_MENTEE',
  PD_MENTOR = 'PD_MENTOR',
  PD_MENTEE = 'PD_MENTEE',
  COMMUNITY_MEMBER = 'COMMUNITY_MEMBER',
}

export enum MentorshipGroup {
  ORGANIZER = 'ORGANIZER',
  PARTICIPANT = 'PARTICIPANT',
}

export enum StatsType {
  OFFERS = 'offers',
  INTERVIEWS = 'interviews',
  TIMELINE = 'timeline',
  LOGOS = 'logos',
}

export enum ProgramRole {
  PROGRAM_MANAGER = 'PROGRAM_MANAGER',
  PROGRAM_FOUNDER = 'PROGRAM_FOUNDER',
  PROGRAM_ADVISOR = 'PROGRAM_ADVISOR',
  SWE_PROGRAM_LEAD = 'SWE_PROGRAM_LEAD',
  SWE_RISING_LEAD = 'SWE_RISING_LEAD',
  SWE_LEAD = 'SWE_LEAD',
  SWE_INACTIVE_LEAD = 'SWE_INACTIVE_LEAD',
  SWE_MENTOR = 'SWE_MENTOR',
  SWE_EXMENTEE_INACTIVE_MENTOR = 'SWE_EXMENTEE_INACTIVE_MENTOR',
  SWE_EXMENTEE_MENTOR = 'SWE_EXMENTEE_MENTOR',
  SWE_EXMENTEE_LOGISTICS_SUPPORT = 'SWE_EXMENTEE_LOGISTICS_SUPPORT',
  SWE_MENTEE = 'SWE_MENTEE',
  PD_MENTOR = 'PD_MENTOR',
  PD_MENTEE = 'PD_MENTEE',
}

export enum Department {
  SWE = 'SWE',
  PD = 'PD',
}

export enum JobTitle {
  SOFTWARE_ENGINEER = 'SOFTWARE_ENGINEER',
  DATA_SCIENTIST = 'DATA_SCIENTIST',
  PRODUCT_DESIGNER = 'PRODUCT_DESIGNER',
  DATA_ENGINEER = 'DATA_ENGINEER',
}

export enum JobFunction {
  SOFTWARE_ENGINEER = 'SOFTWARE_ENGINEER',
  DATA_SCIENTIST = 'DATA_SCIENTIST',
  PRODUCT_DESIGNER = 'PRODUCT_DESIGNER',
  DATA_ENGINEER = 'DATA_ENGINEER',
}

export enum JobType {
  INTERNSHIP = 'INTERNSHIP',
  NEW_GRAD = 'NEW_GRAD',
  INDUSTRY = 'INDUSTRY',
}

export enum LinkProcessStage {
  UNKNOWN_FAILED = 'UNKNOWN_FAILED',
  NOT_PROCESSED = 'NOT_PROCESSED',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  SCRAPING_FAILED = 'SCRAPING_FAILED',
  EXTRACTION_FAILED = 'EXTRACTION_FAILED',
  SUCCESS = 'SUCCESS',
}
