export const LINK_PROCESSING_MOCK_ENV = {
  GOOGLE_GEMINI_API_KEY: '',
  GOOGLE_SAFE_BROWSING_API_KEY: '',
  API_URL: '',
  SERVICE_JWT_SECRET: '',
  SERVICE_NAME: '',
  AUDIENCE_SERVICE_NAME: '',
  NODE_ENV: 'TEST',
};
