"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.StatsType = exports.MentorshipGroup = exports.MentorshipRole = exports.OfferChannel = exports.OfferType = exports.CompanyName = exports.InterestLevel = exports.Permission = exports.UserRole = exports.LinkStatus = exports.JobPostingLocation = exports.InvitationStatus = exports.InterviewStatus = exports.InterviewType = exports.ApplicationStatus = void 0;
var ApplicationStatus;
(function (ApplicationStatus) {
    ApplicationStatus["SUBMITTED"] = "SUBMITTED";
    ApplicationStatus["IN_PROGRESS"] = "IN_PROGRESS";
    ApplicationStatus["OFFER"] = "OFFER";
    ApplicationStatus["REJECTED"] = "REJECTED";
    ApplicationStatus["OA_RECEIVED"] = "OA_RECEIVED";
    ApplicationStatus["WITHDRAWN"] = "WITHDRAWN";
})(ApplicationStatus || (exports.ApplicationStatus = ApplicationStatus = {}));
var InterviewType;
(function (InterviewType) {
    InterviewType["CRITICAL_THINKING"] = "CRITICAL_THINKING";
    InterviewType["CODE_REVIEW"] = "CODE_REVIEW";
    InterviewType["TECHNICAL_LC_CODING"] = "TECHNICAL_LC_CODING";
    InterviewType["OVERALL_BEHAVIORAL"] = "OVERALL_BEHAVIORAL";
    InterviewType["PROJECT_WALKTHROUGH"] = "PROJECT_WALKTHROUGH";
    InterviewType["SYSTEM_DESIGN"] = "SYSTEM_DESIGN";
    InterviewType["RECRUITER_SCREEN"] = "RECRUITER_SCREEN";
    InterviewType["HIRING_MANAGER"] = "HIRING_MANAGER";
    InterviewType["TRIVIA_CONCEPT"] = "TRIVIA_CONCEPT";
    InterviewType["PRACTICAL_CODING"] = "PRACTICAL_CODING";
    InterviewType["DEBUGGING"] = "DEBUGGING";
})(InterviewType || (exports.InterviewType = InterviewType = {}));
var InterviewStatus;
(function (InterviewStatus) {
    InterviewStatus["PASSED"] = "PASSED";
    InterviewStatus["FAILED"] = "FAILED";
    InterviewStatus["WITHDRAWN"] = "WITHDRAWN";
    InterviewStatus["UPCOMING"] = "UPCOMING";
    InterviewStatus["PENDING"] = "PENDING";
})(InterviewStatus || (exports.InterviewStatus = InterviewStatus = {}));
var InvitationStatus;
(function (InvitationStatus) {
    InvitationStatus["ACCEPTED"] = "ACCEPTED";
    InvitationStatus["EXPIRED"] = "EXPIRED";
    InvitationStatus["PENDING"] = "PENDING";
    InvitationStatus["REVOKED"] = "REVOKED";
})(InvitationStatus || (exports.InvitationStatus = InvitationStatus = {}));
var JobPostingLocation;
(function (JobPostingLocation) {
    JobPostingLocation["US"] = "US";
    JobPostingLocation["CANADA"] = "CANADA";
})(JobPostingLocation || (exports.JobPostingLocation = JobPostingLocation = {}));
var LinkStatus;
(function (LinkStatus) {
    LinkStatus["PENDING"] = "PENDING";
    LinkStatus["APPROVED"] = "APPROVED";
    LinkStatus["REJECTED"] = "REJECTED";
})(LinkStatus || (exports.LinkStatus = LinkStatus = {}));
var UserRole;
(function (UserRole) {
    UserRole["ADMIN"] = "ADMIN";
    UserRole["MODERATOR"] = "MODERATOR";
    UserRole["USER"] = "USER";
})(UserRole || (exports.UserRole = UserRole = {}));
var Permission;
(function (Permission) {
    Permission["VIEW_JOB_LINK"] = "VIEW_JOB_LINK";
    Permission["CREATE_JOB_LINK"] = "CREATE_JOB_LINK";
    Permission["MANAGE_JOB_LINK"] = "MANAGE_JOB_LINK";
    Permission["VIEW_JOB_POSTING"] = "VIEW_JOB_POSTING";
    Permission["MANAGE_JOB_POSTING"] = "MANAGE_JOB_POSTING";
    Permission["VIEW_INVITATION"] = "VIEW_INVITATION";
    Permission["MANAGE_INVITATION"] = "MANAGE_INVITATION";
    Permission["VIEW_APPLICATION"] = "VIEW_APPLICATION";
    Permission["MANAGE_APPLICATION"] = "MANAGE_APPLICATION";
})(Permission || (exports.Permission = Permission = {}));
var InterestLevel;
(function (InterestLevel) {
    InterestLevel["LOW"] = "LOW";
    InterestLevel["MEDIUM"] = "MEDIUM";
    InterestLevel["HIGH"] = "HIGH";
})(InterestLevel || (exports.InterestLevel = InterestLevel = {}));
var CompanyName;
(function (CompanyName) {
    CompanyName["SERVICE_NOW"] = "SERVICE_NOW";
    CompanyName["LILLY"] = "LILLY";
    CompanyName["MICROSOFT"] = "MICROSOFT";
    CompanyName["MONGODB"] = "MONGODB";
    CompanyName["BANK_OF_AMERICA"] = "BANK_OF_AMERICA";
    CompanyName["META"] = "META";
    CompanyName["NIANTIC"] = "NIANTIC";
    CompanyName["ROBINHOOD"] = "ROBINHOOD";
    CompanyName["DOORDASH"] = "DOORDASH";
    CompanyName["LINKEDIN"] = "LINKEDIN";
    CompanyName["PROOFPOINT"] = "PROOFPOINT";
    CompanyName["ADOBE"] = "ADOBE";
    CompanyName["AMAZON"] = "AMAZON";
    CompanyName["PLAID"] = "PLAID";
    CompanyName["WAYFAIR"] = "WAYFAIR";
    CompanyName["GODADDY"] = "GODADDY";
    CompanyName["MATSON_MONEY"] = "MATSON_MONEY";
    CompanyName["SAP"] = "SAP";
    CompanyName["HEROKU"] = "HEROKU";
    CompanyName["MORGAN_STANLEY"] = "MORGAN_STANLEY";
    CompanyName["SHOPIFY"] = "SHOPIFY";
    CompanyName["MASTERCARD"] = "MASTERCARD";
    CompanyName["SLACK"] = "SLACK";
    CompanyName["LIBERTY_MUTUAL_INSURANCE"] = "LIBERTY_MUTUAL_INSURANCE";
    CompanyName["HELMERICH_PAYNE"] = "HELMERICH_PAYNE";
    CompanyName["GRAMMARLY"] = "GRAMMARLY";
    CompanyName["BNY_MELLON"] = "BNY_MELLON";
    CompanyName["PAYPAL"] = "PAYPAL";
    CompanyName["GOLDMAN_SACHS"] = "GOLDMAN_SACHS";
    CompanyName["EBAY"] = "EBAY";
    CompanyName["VERISK"] = "VERISK";
    CompanyName["HUBSPOT"] = "HUBSPOT";
    CompanyName["EXPEDIA"] = "EXPEDIA";
    CompanyName["ORACLE"] = "ORACLE";
    CompanyName["EXPERIAN"] = "EXPERIAN";
    CompanyName["WAYMO"] = "WAYMO";
    CompanyName["ASANA"] = "ASANA";
    CompanyName["MCDONALDS"] = "MCDONALDS";
    CompanyName["BUBBLE_IO"] = "BUBBLE_IO";
    CompanyName["KENCO_GROUP"] = "KENCO_GROUP";
    CompanyName["COINBASE"] = "COINBASE";
    CompanyName["FOREFLIGHT"] = "FOREFLIGHT";
    CompanyName["QUALCOMM"] = "QUALCOMM";
    CompanyName["PALANTIR"] = "PALANTIR";
    CompanyName["BLOOMBERG"] = "BLOOMBERG";
    CompanyName["GOOGLE"] = "GOOGLE";
    CompanyName["UKG"] = "UKG";
    CompanyName["SENTRY"] = "SENTRY";
    CompanyName["PLAYSTATION"] = "PLAYSTATION";
    CompanyName["RYCO"] = "RYCO";
    CompanyName["NVIDIA"] = "NVIDIA";
    CompanyName["HIGHMARK_HEALTH"] = "HIGHMARK_HEALTH";
    CompanyName["HEALTH_ENHANCEMENT_SYSTEMS"] = "HEALTH_ENHANCEMENT_SYSTEMS";
})(CompanyName || (exports.CompanyName = CompanyName = {}));
var OfferType;
(function (OfferType) {
    OfferType["INTERNSHIP"] = "INTERNSHIP";
    OfferType["NEW_GRAD"] = "NEW_GRAD";
})(OfferType || (exports.OfferType = OfferType = {}));
var OfferChannel;
(function (OfferChannel) {
    OfferChannel["EXTERNAL"] = "EXTERNAL";
    OfferChannel["RETURN_OFFER"] = "RETURN_OFFER";
})(OfferChannel || (exports.OfferChannel = OfferChannel = {}));
var MentorshipRole;
(function (MentorshipRole) {
    MentorshipRole["PROGRAM_MANAGER"] = "PROGRAM_MANAGER";
    MentorshipRole["PROGRAM_FOUNDER"] = "PROGRAM_FOUNDER";
    MentorshipRole["PROGRAM_ADVISOR"] = "PROGRAM_ADVISOR";
    MentorshipRole["SWE_PROGRAM_LEAD"] = "SWE_PROGRAM_LEAD";
    MentorshipRole["SWE_RISING_LEAD"] = "SWE_RISING_LEAD";
    MentorshipRole["SWE_LEAD"] = "SWE_LEAD";
    MentorshipRole["SWE_INACTIVE_LEAD"] = "SWE_INACTIVE_LEAD";
    MentorshipRole["SWE_MENTOR"] = "SWE_MENTOR";
    MentorshipRole["SWE_EXMENTEE_INACTIVE_MENTOR"] = "SWE_EXMENTEE_INACTIVE_MENTOR";
    MentorshipRole["SWE_EXMENTEE_MENTOR"] = "SWE_EXMENTEE_MENTOR";
    MentorshipRole["SWE_EXMENTEE_LOGISTICS_SUPPORT"] = "SWE_EXMENTEE_LOGISTICS_SUPPORT";
    MentorshipRole["SWE_MENTEE"] = "SWE_MENTEE";
    MentorshipRole["PD_MENTOR"] = "PD_MENTOR";
    MentorshipRole["PD_MENTEE"] = "PD_MENTEE";
})(MentorshipRole || (exports.MentorshipRole = MentorshipRole = {}));
var MentorshipGroup;
(function (MentorshipGroup) {
    MentorshipGroup["ORGANIZER"] = "ORGANIZER";
    MentorshipGroup["PARTICIPANT"] = "PARTICIPANT";
})(MentorshipGroup || (exports.MentorshipGroup = MentorshipGroup = {}));
var StatsType;
(function (StatsType) {
    StatsType["OFFERS"] = "offers";
    StatsType["INTERVIEWS"] = "interviews";
    StatsType["TIMELINE"] = "timeline";
    StatsType["LOGOS"] = "logos";
})(StatsType || (exports.StatsType = StatsType = {}));
